config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
#   , :controllers => { reviews: 'users/reviews' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :courses, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit]
    # resources :classes, only: [:new, :create]
    #list meilleur prof
    collection do
        get :best
    end
    #list meilleur cour
    collection do
        get :featured
    end
  end

  resources :classes, only: [:show, :index] do
    resources :enrollments, only: [:new, :create]
  end

  resources :enrollments, only: [:index, :update, :destroy] do
    member do
      patch :validate
      patch :reject
    end
  end

  namespace :teacher do
    resources :courses, only: [:show, :new, :create, :index, :update, :edit, :destroy] do
        resources :classes, only: [:new, :create]
    end
    resources :classes, only: [:show, :index, :update, :edit, :destroy]

    resources :enrollments, only: [:index, :update, :edit, :destroy]
    resources :reviews, only: [:index, :show] do
      collection do
        get :top
      end
    end
  end

    # namespace :users do
    #     resources :reviews, only: [:destroy]
    # end

  get :teachers, to: 'users#index'
  get 'teachers/:id', to: 'users#show', as: :teacher

  get :my_profil, to: 'users#my_profil'
  get :dashboard, to: 'users#dashboard'
  resources :reviews, only: [:destroy]

#   delete :dashboard, to: 'users#destroyreview'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :courses, through: :classes
  has_many :courses
  has_many :reviews, through: :courses
  has_many :reviews
  has_many :enrollments

  # validates :first_name, presence: true
  # validates :last_name, presence: true
  # validates :email, confirmation: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
#   before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update ]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:status])
  end

  # The path used after sign up.
#   def after_sign_up_path_for(resource)
#     super(resource)
#   end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_my_profil, only: %i[ my_profil dashboard ]

    def index
        @teachers = User.where(status: 'teacher')
    end

    def show
        @teacher = User.find(params[:id])
    end

    def my_profil
    end

    def dashboard
        @courses = current_user.courses
        @review = Review.new
        # @enrollment = Enrollment.where(user_id: current_user)
        # @reviews = Review.where(user_id: current_user)


        # @course = Course.find(params[:id])
        # @classes = @course.course_classes
        # @classes_uniq = @classes.group_by { |classe| classe.name }

    end

    # def destroyreview
    #     Review.find(params[:id]).destroy
    #     redirect_to dashboard_path
    # end

    private

    def set_my_profil
        @user = current_user
    end

    # def set_courses
    #     @course = Course.find(params[:id])
    # end
end

app/views/users/dashboard.html.erb
<div class="dashboard-container">
    <div class="dashboard-container-profil">

        <div class="dashboard-avatar-container">
            <div class="dashboard-profil-img-container">
                <% if current_user.url_avatar %>
                    <%= image_tag(current_user.url_avatar, class: "dashboard-profil-img") %>
                <% else %>
                    <%= image_tag("avatar-neutre.jpg", class: "user-card-img") %>
                <% end %>
            </div>
            <p><%= current_user.first_name %> <%= current_user.last_name %></p>
            <p><%= current_user.status %></p>
            <%= link_to "Edit", edit_user_registration_path, class: "btn-aka-light-login btn-profil-edit" %>
            <p><i class="fa-solid fa-users"></i> 2 followers</p>
        </div>
        <!-------------->
                <div class="aka-line-60-grey-container">
                    <div class="aka-line-60-grey"></div>
                </div>
            <!-------------->
        <div class="dashboard-list-container">
            <ul>
                <li>Parameters</li>
                <li>Change my status</li>
                <li>Check my wallet</li>
                <li>My info</li>
            </ul>
        </div>
    </div>
    <div class="dashboard-container-content">

        <div class="dashboard-list-container">
            <ul>
                <li>Following classes</li>
                <li>Graduation</li>
                <li>Message</li>
                <li>My reviews</li>
                <li>Configuration</li>
            </ul>
        </div>
        <!-------------->
                <div class="aka-line-80-primary-container">
                    <div class="aka-line-80-primary"></div>
                </div>
        <!-------------->
        <div class="dashboard-container-centent">
            <h2 class="dashboard-list-title" style="color:green">Ongoing Class</h2>
            <% @user.enrollments.each do |enrollment| %>
                <% if (enrollment.classe.start_date > Time.now) %>

                    <div class="course-classe-container">
                        <div  class="d-flex">
                            <div class="course-category-img-container">
                                <%= link_to course_path(enrollment.classe.course) do %>
                                    <%= image_tag("#{enrollment.classe.course.category}.jpg", class: "course-category-img") %>
                                <% end %>

                            </div>
                            <div class="course-category-info-container">
                                <h2><%= enrollment.classe.course.title %></h2>
                                <h3><%= enrollment.classe.name %></h3>
                                <p><%= enrollment.classe.start_date %></p>
                            </div>
                        </div>
                        <div class="course-category-right-container">
                            <p> duration : <%= enrollment.classe.end_date.hour - enrollment.classe.start_date.hour %>h00</p>
                            <%= button_to "Cancel", enrollment_path(enrollment), method: :delete, class: "btn-aka-light-login", data: {turbo_confirm: 'are you sure ?'}  %>
                        </div>
                    </div>

                <% end %>
            <% end %>

            <!-------------->
                <div class="aka-line-60-grey-container">
                    <div class="aka-line-60-grey"></div>
                </div>
            <!-------------->
            <h3 class = "d-flex justify-content-center">Student feedback</h3>
            <h2 class="dashboard-list-title" style="color:red">Terminated Class</h2>
            <% @user.enrollments.each do |enrollment| %>
                <% if (enrollment.classe.start_date < Time.now) %>
                    <div class="course-classe-container">
                        <div class="d-flex">
                            <div class="course-category-img-container">
                                <%= link_to course_path(enrollment.classe.course) do %>
                                    <%= image_tag("#{enrollment.classe.course.category}.jpg", class: "course-category-img") %>
                                <% end %>
                            </div>
                            <div class="course-category-info-container">
                                <h3><%= enrollment.classe.name %></h3>
                                <p><%= enrollment.classe.start_date %></p>
                            </div>
                        </div>
                        <div class = "container d-flex justify-content-end">
                          <%= button_to "Delete", enrollment_path(enrollment), method: :delete, class: "btn-aka-light-login", data: {turbo_confirm: 'are you sure ?'}  %>
                        </div>
                    </div>

                    <div class="course-classe-container-review">

                        <% reviews = enrollment.classe.course.reviews.where(user_id: current_user.id) %>
                        <% if reviews.length > 0 %>
                            <% reviews.each do |review| %>
                                <div class="all-classes-review">
                                    <div class="classes-review">
                                        <% if (review.rating != nil)  %>
                                            <% review.rating.times do %>
                                                <i class="fa-solid fa-star" style="color: #e5c006;"></i>
                                            <% end %>
                                        <% end %>
                                        <p><i class="fa-sharp fa-regular fa-comment-dots"></i> <%= review.comment %></p>
                                    </div>
                                </div>

                                    <%= button_to "Delete", review_path(review), method: :delete, class: "btn-aka-light-login", data: {turbo_confirm: 'are you sure ?'}  %>
                            <% end %>

                        <% else %>
                            <%= simple_form_for @review, url: course_reviews_path(enrollment.classe.course),  html: {class: "add-classes-revdwdwiew"} do |f| %>
                                <div class= "add-classes-review">
                                    <div class="d-flex">
                                        <%= f.error_notification %>
                                        <%= f.input :comment,
                                                label: false,
                                                placeholder: "Add a comment", as: :text, :input_html => { class: 'add-review-form-input first-review-input'}
                                                %>
                                        <%= f.input :rating,
                                                label: false,
                                                value: 6,
                                                placeholder: "Add a rating",
                                                input_html: { class: 'add-review-form-input'}%>
                                    </div>
                                    <div >
                                        <%= f.button :submit, class: "btn-aka-light-login" %>
                                    </div>
                                </div>

                            <% end %>

                        <% end %>

                    </div>
                <% end %>

            <% end %>
        </div>

    </div>
</div>

app/views/users/index.html.erb
<h1>Teachers</h1>

<% @teachers.each do |teacher| %>
    <div class="card teacher-card" style="width: 18rem;">
    <img src="https://images.unsplash.com/photo-1503945438517-f65904a52ce6?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80" class="card-img-top" alt="...">
        <div class="card-body">
            <h3><%= teacher.first_name %> <%= teacher.last_name %></h3>

            <p class="card-text"><%= teacher.profil %></p>
        </div>
    </div>
<% end %>

app/views/users/my_profil.html.erb
<div class="profil-container mt-2">
  <div class="user-info">
    <div class= "user-card-img-container">
        <% if current_user.url_avatar %>
            <img src="<%= current_user.url_avatar %>" alt="profile one" class= "user-card-img">
        <% else %>
            <%= image_tag("avatar-neutre.jpg", class: "user-card-img") %>
        <% end %>
    </div>
    <div class = "container m-3 mp-3">
      <div class="text-start">
        <p><strong><i class="fa-solid fa-id-card"></i></strong> <%= current_user.first_name %> <%= current_user.last_name %></p>
        <%# <p><strong><i class="fa-solid fa-id-card"></i></strong> <%= current_user.last_name %>
        <p><strong><i class="fa-solid fa-envelope"></i></strong> <%= current_user.email %></p>
        <p><strong><i class="fa-solid fa-user-tie"></i></strong> <%= current_user.status %></p>
      </div>
      <%= link_to "edit", edit_user_registration_path, class: "btn-aka-light-login" %>

    </div>
  </div>

</div>

app/views/users/show.html.erb
<div class="container mt-2">
    <div class="teacher-cardshowing">
        <h2><%= @teacher.first_name %> <%= @teacher.last_name %></h2>
        <div class="teacher-rating">
            <% average_rating = @teacher.courses.average(:rating) %>
            <% average_rating.to_i.times do %>
                <i class="fa-solid fa-star" style="color: #d1c300;"></i>
            <% end %>
        </div>
        <div class="show-teacher-line-container">
            <div class="aka-line-80-primary-container">
                <div class="aka-line-80-primary"></div>
            </div>
        </div>

        <% if @teacher.url_avatar %>
            <img src="<%= @teacher.url_avatar %>" alt="profile one" class= "teacher-card-img-sqdqdub">
        <% else %>
            <%= image_tag("avatar-neutre.jpg", class: "teacher-card-img-sudwqdqb") %>
        <% end %>
    </div>

    <% @teacher.courses.each do |course| %>
        <% if course.reviews.any? %>
            <div class="show-teacher-line-container">
                <div class="aka-line-80-primary-container">
                    <div class="aka-line-80-primary"></div>
                </div>
            </div>

            <div class="teacher-card-show">
                <h5><strong><%= course.name %></strong></h5>

                <% course.reviews.each do |review| %>
                    <div class="teacher-card-container-sub">
                        <div class="teacher-img-container">
                            <strong><%= review.user.first_name %> <%= review.user.last_name %></strong>
                        </div>

                        <div class="teacher-info-container">
                            <%= review.comment %>
                        </div>

                        <div class="teacher-rating-container">
                            <% review.rating.times do %>
                            <i class="fa-solid fa-star" style="color: #d1c300;"></i>
                            <% end %>
                        </div>
                    </div>
                <% end %>

            </div>
        <% end %>
    <% end %>
</div>