config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
#   , :controllers => { reviews: 'users/reviews' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :courses, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit]
    # resources :classes, only: [:new, :create]
    #list meilleur prof
    collection do
        get :best
    end
    #list meilleur cour
    collection do
        get :featured
    end
  end

  resources :classes, only: [:show, :index] do
    resources :enrollments, only: [:new, :create]
  end

  resources :enrollments, only: [:index, :update, :destroy] do
    member do
      patch :validate
      patch :reject
    end
  end

  namespace :teacher do
    resources :courses, only: [:show, :new, :create, :index, :update, :edit, :destroy] do
        resources :classes, only: [:new, :create]
    end
    resources :classes, only: [:show, :index, :update, :edit, :destroy]

    resources :enrollments, only: [:index, :update, :edit, :destroy]
    resources :reviews, only: [:index, :show] do
      collection do
        get :top
      end
    end
  end

    # namespace :users do
    #     resources :reviews, only: [:destroy]
    # end

  get :teachers, to: 'users#index'
  get 'teachers/:id', to: 'users#show', as: :teacher

  get :my_profil, to: 'users#my_profil'
  get :dashboard, to: 'users#dashboard'
  resources :reviews, only: [:destroy]

#   delete :dashboard, to: 'users#destroyreview'
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="sub-container">
        <h3>Akademics Business</h3>
        <ul>
            <li><a href="#">Teach on Akademics</a></li>
            <li><a href="#">Get the app</a></li>
            <li><a href="#">About us</a></li>
            <li><a href="#">Contact us</a></li>
        </ul>
    </div>
    <div class="sub-container">
        <h3>Careers</h3>
        <ul>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Help and Support</a></li>
            <li><a href="#">Affiliate</a></li>
            <li><a href="#">Investors</a></li>
        </ul>
    </div>
    <div class="sub-container">
        <h3>Terms</h3>
        <ul>
            <li><a href="#">Privacy policy</a></li>
            <li><a href="#">Cookie settings</a></li>
            <li><a href="#">Sitemap</a></li>
            <li><a href="#">Accessibility statement</a></li>
        </ul>
    </div>
    <div  class="vertical-line">
    </div>
    <div class="sub-container">
        <%# <h3>Contact Us</h3> %>
        <p>info@akademics.com</p>
        <p>123-456-7890</p>
    </div>
    <div class="social-media">
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="faka">
        <p>©Akademics 2023 | All rights reserved.</p>
        <%# <a href="#" class="back-to-top">Back to top</a> %>
    </div>
</footer>

app/views/shared/_gototop.html.erb
<div class="d-none" data-controller="gototop" data-gototop-target="gototop">
    <%= link_to '#', class: 'gototop btn-aka-light square' do %>
        <i class="fa-solid fa-arrow-up"></i>
    <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbarr shadow-lg bg-body-tertiary">
    <div class="navbar-container" data-dotaka-target="navbar">
        <%# --------------------- navbar left ---------------------%>
        <%= link_to root_path, class: "navbar-left" do %>
            <div class="logo-letter">
                <div></div>
                <h1>A</h1>
            </div>
            <h1 class="logo-letter-rest">kademics</h1>
            <div class="dot-aka" data-dotaka-target="dotaka"></div>
        <% end %>

        <%# --------------------- navbar middle ---------------------%>
        <ul class="navbar-middle">

            <div class="burger-menu">
                <i class="fa-solid fa-bars"></i>
            </div>

            <div class="d-flex">
                <%= link_to courses_path, class: 'v' do %>
                    <li class="nav-item <%= active_class(courses_path) %>" data-dotaka-target="courses" data-action="mouseover->dotaka#mouseOver1 mouseout->dotaka#mouseOut1">
                        Courses
                    </li>
                <% end %>

                <%= link_to courses_path, class: 'v' do %>
                    <li class="nav-item" data-dotaka-target="profil" data-action="mouseover->dotaka#mouseOver2 mouseout->dotaka#mouseOut2">
                        Category
                    </li>
                <% end %>

                <% if !current_user %>
                    <%= link_to edit_user_registration_path, class: 'd-flex align-middle ' do %>
                        <li class="nav-item " data-dotaka-target="dashboard" data-action="mouseover->dotaka#mouseOver3 mouseout->dotaka#mouseOut3">
                            Become teacher
                            <i class="fa-solid fa-person-chalkboard"></i>
                        </li>
                    <% end %>
                <% elsif (current_user.status == 'student' || current_user.status == nil)%>
                    <%= link_to edit_user_registration_path, class: 'd-flex align-middle ' do %>
                        <li class="nav-item <%= active_class(edit_user_registration_path) %>" data-dotaka-target="dashboard" data-action="mouseover->dotaka#mouseOver3 mouseout->dotaka#mouseOut3">
                            Become teacher
                            <i class="fa-solid fa-person-chalkboard"></i>
                        </li>
                    <% end %>
                <% end %>
            </div>

            <li class="search-bar mysearch-bar " data-controller="searchtoggle">
                <div class="search-container d-none " data-searchtoggle-target="searchtoggle">
                    <%= form_with url: root_path, method: :get, class: "d-flex" do %>
                        <%= text_field_tag :query,
                            params[:query],
                            # class: "form-control",
                            placeholder: "Find a Cours"
                        %>
                        <%= submit_tag "Search", class: "btn-aka search_bar_button "%>
                    <% end %>
                </div>
                <i class="fa-solid fa-magnifying-glass nav-item" data-action="click->searchtoggle#toggle"></i>
            </li>
        </ul>

        <%# --------------------- navbar right ---------------------%>
        <ul class="navbar-right">
            <%= link_to "/", class: 'c' do %>
                <li class="nav-item">
                    <i class="fa-solid fa-cart-shopping"></i>
                </li>
            <% end %>

            <% if user_signed_in? %>

                <%= link_to "/", class: 'navbar-message-icon' do %>
                    <i class="fa-regular fa-message"></i>
                <% end %>


                <li class="nnn" data-controller="menutoggle">
                    <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown">
                        <% if current_user.url_avatar %>
                            <%= image_tag("#{current_user.url_avatar}", class: "avatar", data: { action: "click->menutoggle#toggle" }) %>
                        <% else %>
                            <%= image_tag("avatar-neutre.jpg", class: "avatar", data: { action: "click->menutoggle#toggle" }) %>
                        <% end %>
                    </a>
                    <div data-menutoggle-target="menu" class="d-none menu-profil">
                        <%= link_to "Profil", my_profil_path, class: "dropdown-item" %>
                        <% if current_user.status == 'teacher'  %>
                            <%= link_to "My Teaching", teacher_courses_path, class: "dropdown-item" %>
                        <% end %>
                        <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
                        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
                    </div>
                </li>

            <% else %>

                <li class="nav-item">
                    <%= link_to "Login", new_user_session_path, class: "nav-link btn-aka-light-login" %>
                </li>

            <% end %>
         </ul>

  </div>
</div>