config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
#   , :controllers => { reviews: 'users/reviews' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :courses, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit]
    # resources :classes, only: [:new, :create]
    #list meilleur prof
    collection do
        get :best
    end
    #list meilleur cour
    collection do
        get :featured
    end
  end

  resources :classes, only: [:show, :index] do
    resources :enrollments, only: [:new, :create]
  end

  resources :enrollments, only: [:index, :update, :destroy] do
    member do
      patch :validate
      patch :reject
    end
  end

  namespace :teacher do
    resources :courses, only: [:show, :new, :create, :index, :update, :edit, :destroy] do
        resources :classes, only: [:new, :create]
    end
    resources :classes, only: [:show, :index, :update, :edit, :destroy]

    resources :enrollments, only: [:index, :update, :edit, :destroy]
    resources :reviews, only: [:index, :show] do
      collection do
        get :top
      end
    end
  end

    # namespace :users do
    #     resources :reviews, only: [:destroy]
    # end

  get :teachers, to: 'users#index'
  get 'teachers/:id', to: 'users#show', as: :teacher

  get :my_profil, to: 'users#my_profil'
  get :dashboard, to: 'users#dashboard'
  resources :reviews, only: [:destroy]

#   delete :dashboard, to: 'users#destroyreview'
end

app/controllers/courses_controller.rb
require "open-uri"
require "nokogiri"

class CoursesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]
    before_action :set_courses, only: [:show, :edit, :update, :destroy]

    def scrap
        url = "https://www.britannica.com/art/English-literature/Playwrights-after-Shakespeare"
        html_file = URI.open(url).read
        html_doc = Nokogiri::HTML.parse(html_file)
        html_doc.search(".standard-card-new__article-title").each do |element|
            # puts element.text.strip
            element.attribute("href").value
        end
    end


    def index
        @courses = Course.all
        @courses_uniq = Course.all.uniq { |course| course[:category] }
    end

    def show
        @enrollment = Enrollment.new
        @classes = @course.course_classes
        # @scrap = scrap()
        # @enrollment = Enrollment.where(user_id: current_user)
    end

    def featured
        # @reviews = Review.find(params[:review_id])
        @courses = Course.where(rating: 5)
        # @courses = Course.where(rating: 5).joins(:classe)
        # @courses = Course.where(rating: 5).includes(:classe)
    end

    def best
        # @teachers = User.where(["status = ? and rating = ?", "teacher", 5])
        @teachers = User.where(status: 'teacher')
    end

    private

    def set_courses
        @course = Course.find(params[:id])
    end
end

app/controllers/teacher/classes_controller.rb
class Teacher::ClassesController < ApplicationController
    def index
        # @enrollment = Enrollment.where(user_id: current_user)
    end

    def new
        @classe = Classe.new
        @course = Course.find(params[:course_id])
    end

    def create
        @classe = Classe.new(classe_params)
        @classe.course = Course.find(params[:course_id])
        @classe.save!
        redirect_to teacher_course_path(params[:course_id])
    end

    def destroy
        @classe = Classe.find(params[:id]).destroy
        redirect_to teacher_course_path(@classe.course)
        # respond_to do |format|
        #   format.html { redirect_to booking_url, notice: "Booking was successfully destroyed." }
        #   format.json { head :no_content }
        # end
    end

    private

    def classe_params
        params.require(:classe).permit(:name, :start_date, :end_date, :max_people)
    end
end

app/controllers/teacher/courses_controller.rb
class Teacher::CoursesController < ApplicationController

    # skip_before_action :authenticate_user!, only: [:index, :show]
    before_action :set_course, only: %i[ show ]

    def index
        @courses = Course.where(user_id: current_user)
    end

    def show
        @classes = @course.course_classes
    end

    def edit
    end

    def update

    end

    def new
        @course = Course.new
    end

    def create
        @course = Course.new(course_params)
        @course.user = current_user
        @course.save!
        redirect_to teacher_courses_path
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy
        redirect_to teacher_courses_path
    end

    private

    def set_course
        @course = Course.find(params[:id])
    end

    def course_params
        params.require(:course).permit(:name, :title, :description, :price, :content, :grade, :category)
    end
end

app/controllers/teacher/enrollments_controller.rb
class Teacher::EnrollmentsController < ApplicationController
    def index

    end
end

app/controllers/teacher/reviews_controller.rb
class Teacher::ReviewsController < ApplicationController
    def index

    end
end

app/views/teacher/courses/index.html.erb
<div class ="course-index-container">
    <div class="course-index-card-container">
        <% @courses.each do |course| %>
            <div class='course-index-card'>
                <%= link_to teacher_course_path(course) do %>
                    <div class= "course-card-sub">
                        <% if course.category %>
                            <%= image_tag("#{course.category}.jpg", class: "course-card-img") %>
                        <% end %>

                        <div class="courses-card-info">
                            <h3 class="card-title  <%= course.category%>"><%= course.name %></h3>
                            <h5 class="card-title"><%= course.title %></h5>
                            <p class="card-name"> <%= course.user.first_name %> <%= course.user.last_name %></p>
                            <p class="card-price"><%= course.price %> $</p>

                            <h6 class="card-name"><%= course.name %></h6>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>
  <div class = "container d-flex justify-content-center">
    <%= link_to "Create a new course", "courses/new", class: "btn-aka-light-login" %>
  </div>

<!---- test my server>

app/views/teacher/courses/new.html.erb
 <div class="container w-75 p-3 d-flex flex-column align-items-center">

    <%= simple_form_for @course, url: teacher_courses_path(@course),  html: {class: "w-50 p-3"} do |f| %>
        <h2 class = "text-center">Add a course</h2>
        <%= f.error_notification %>
        <%# <%= f.error_notification message: f.object.errors[:base].to_sentence if %>
        <%= f.input :name,
                    label: false,
                    placeholder: "Name" %>
        <%= f.input :title,
                    label: false,
                    placeholder: "Title" %>
        <%= f.input :description,
                    label: false,
                    placeholder: "Description" %>
        <%= f.input :price,
                    label: false,
                    placeholder: "Price" %>
        <%= f.input :content,
                    label: false,
                    placeholder: "Content" %>
        <%= f.input :category,
                    label: false,
                    :collection => [ "Category","literature", "art", "mathematics", "physics", "robotic", "chemistry", "engineering"], selected:  "Category"%>
        <%= f.input :grade,
                    label: false,
                    placeholder: "Grade" %>
        <div>
          <%= f.button :submit, class: "btn-aka-light-login"%>
        </div>
    <% end %>
</div>

app/views/teacher/courses/show.html.erb
<%# <div class ="container"> %>
<!--------------------------------------->
<div class = "course-show-container">
  <div class="courses-show-banner-container">
        <h3 class="courses-show-category <%= @course.category%>"><%= @course.category.capitalize %></h3>
        <div class="courses-show-banner-container-sub0">
            <div class="courses-show-banner-container-sub">
                <div class="courses-show-banner-gradient"></div>
                  <%= image_tag("#{@course.category}.jpg", class: "course-show-img") %>
                  <div class="courses-show-banner-info">
                    <h2 class="courses-show-title <%= @course.category%>"><%= @course.title %> </h2>
                    <h2 class="courses-show-name"><%= @course.name%></h2>
                  </div>
                </div>
            </div>
            <div class="d-flex justify-content-around">
              <%= link_to "Edit", "edit", class: "btn-aka-light-login" %>
              <%= button_to "Delete", teacher_course_path(@course), method: :delete, class: "btn-aka-light-login", data: {turbo_confirm: 'are you sure ?'}  %>
            </div>
        </div>
  </div>
</div>
<!--------------------------------------->
        <div class="home-container">
          <div class="aka-line-80-primary-container">
            <div class="aka-line-80-primary"></div>
          </div>
        </div>


<!--------------------------------------->
<div class = "course-show-container">
    <div class = "session-container">
            <% @classes.each do |classe| %>

                <div class="session-container-sub">
                    <div class="session-img-container">
                        <%= image_tag("#{@course.category}.jpg", class: "session-img") %>
                    </div>

                    <div class="session-info-container">
                        <h3 class="<%= @course.category%>" >  <%= classe.name %></h3>
                        <p> <i class="fa-solid fa-calendar-days"></i> <%= classe.start_date %></p>
                        <p> <i class="fa-solid fa-hourglass-start"></i> <%= classe.start_date.hour %>h00</p>
                        <p> <i class="fa-solid fa-hourglass-end"></i> <%= classe.end_date.hour - classe.start_date.hour %>h00</p>
                    </div>

                    <div class="session-enrollment-container">
                        <p style="color:green">start in : <%= (classe.start_date - Time.now).hour %></p>
                        <p style="color:green">Enrollment Open</p>
                        <p style="color:green"> Available seats <%=  classe.max_people - classe.enrollments.count %> / <%=  classe.max_people %></p>

                         <%= button_to "Delete", teacher_class_path(classe), method: :delete, class: 'btn-aka-light-login', data: {turbo_confirm: 'are you sure ?'}  %>
                    </div>

                </div>

                <div class="enrollment-container">
                        <% if classe.enrollments.any? %>
                            <h4>Registered Students</h4>
                        <% end %>

                        <div class="enrollment-container-sub">
                            <% classe.enrollments.each do |enrollment| %>
                                <div class="enrollment-student-container">
                                    <div class="d-flex">
                                        <div class="enrollment-student-img-container">
                                            <% if enrollment.user.url_avatar %>
                                                <%= image_tag("#{enrollment.user.url_avatar}.jpg", class: "enrollment-student-img") %>
                                            <% else %>
                                                <%= image_tag("avatar-neutre.jpg", class: "enrollment-student-img") %>
                                            <% end %>
                                        </div>
                                        <div class="enrollment-student-info">
                                            <p><%= enrollment.user.first_name %> <%= enrollment.user.last_name %></p>
                                        </div>
                                    </div>
                                    <p><%= enrollment.created_at.strftime("%d/%m/%Y") %></p>
                                </div>
                            <% end %>
                        </div>
                </div>

            <% end %>
        <%# </div> %>
    </div>
</div>
<div class = "container d-flex justify-content-center">
    <%= link_to "Create a new class", new_teacher_course_class_path(@course), class: 'btn-aka-light-login' %>
</div>
</div>
<!--------------------------------------->
<%# </div> %>