config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
#   , :controllers => { reviews: 'users/reviews' }

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :courses, only: [:index, :show] do
    resources :reviews, only: [:new, :create, :edit]
    # resources :classes, only: [:new, :create]
    #list meilleur prof
    collection do
        get :best
    end
    #list meilleur cour
    collection do
        get :featured
    end
  end

  resources :classes, only: [:show, :index] do
    resources :enrollments, only: [:new, :create]
  end

  resources :enrollments, only: [:index, :update, :destroy] do
    member do
      patch :validate
      patch :reject
    end
  end

  namespace :teacher do
    resources :courses, only: [:show, :new, :create, :index, :update, :edit, :destroy] do
        resources :classes, only: [:new, :create]
    end
    resources :classes, only: [:show, :index, :update, :edit, :destroy]

    resources :enrollments, only: [:index, :update, :edit, :destroy]
    resources :reviews, only: [:index, :show] do
      collection do
        get :top
      end
    end
  end

    # namespace :users do
    #     resources :reviews, only: [:destroy]
    # end

  get :teachers, to: 'users#index'
  get 'teachers/:id', to: 'users#show', as: :teacher

  get :my_profil, to: 'users#my_profil'
  get :dashboard, to: 'users#dashboard'
  resources :reviews, only: [:destroy]

#   delete :dashboard, to: 'users#destroyreview'
end

app/controllers/courses_controller.rb
require "open-uri"
require "nokogiri"

class CoursesController < ApplicationController
    skip_before_action :authenticate_user!, only: [:index, :show]
    before_action :set_courses, only: [:show, :edit, :update, :destroy]

    def scrap
        url = "https://www.britannica.com/art/English-literature/Playwrights-after-Shakespeare"
        html_file = URI.open(url).read
        html_doc = Nokogiri::HTML.parse(html_file)
        html_doc.search(".standard-card-new__article-title").each do |element|
            # puts element.text.strip
            element.attribute("href").value
        end
    end


    def index
        @courses = Course.all
        @courses_uniq = Course.all.uniq { |course| course[:category] }
    end

    def show
        @enrollment = Enrollment.new
        @classes = @course.course_classes
        # @scrap = scrap()
        # @enrollment = Enrollment.where(user_id: current_user)
    end

    def featured
        # @reviews = Review.find(params[:review_id])
        @courses = Course.where(rating: 5)
        # @courses = Course.where(rating: 5).joins(:classe)
        # @courses = Course.where(rating: 5).includes(:classe)
    end

    def best
        # @teachers = User.where(["status = ? and rating = ?", "teacher", 5])
        @teachers = User.where(status: 'teacher')
    end

    private

    def set_courses
        @course = Course.find(params[:id])
    end
end

app/controllers/teacher/courses_controller.rb
class Teacher::CoursesController < ApplicationController

    # skip_before_action :authenticate_user!, only: [:index, :show]
    before_action :set_course, only: %i[ show ]

    def index
        @courses = Course.where(user_id: current_user)
    end

    def show
        @classes = @course.course_classes
    end

    def edit
    end

    def update

    end

    def new
        @course = Course.new
    end

    def create
        @course = Course.new(course_params)
        @course.user = current_user
        @course.save!
        redirect_to teacher_courses_path
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy
        redirect_to teacher_courses_path
    end

    private

    def set_course
        @course = Course.find(params[:id])
    end

    def course_params
        params.require(:course).permit(:name, :title, :description, :price, :content, :grade, :category)
    end
end

app/views/courses/best.html.erb
<h1>best teachers</h1>
<% @teachers.each do |teacher| %>
    <h2><%= teacher.first_name %></h2>
    <% teacher.courses.each do |course| %>
        <p><%= course.id %></p>
    <% end %>
<% end %>

app/views/courses/featured.html.erb
<h1>cours en vedette</h1>

<% @courses.each do |course| %>

    <% course.course_classes.each do |classe| %>
        <p><%= classe.name %></p>
    <% end %>

    <h1><%= course.title %></h1>
    <h2><%= course.name %></h2>
<% end %>

app/views/courses/index.html.erb
<!-------------->
<div class ="course-index-container">
    <div class="courses-index-category">

        <% @courses_uniq.each_with_index do |course, i| %>
            <%# <%= link_to courses_path do %>
                <div class="courses-index-category-link"><%= course.category %></div>
            <%# <% end %>
        <% end %>
    </div>

    <div class="course-index-card-container">
        <% @courses.each do |course| %>
            <div class='course-index-card'>
                <%= link_to course_path(course) do %>
                    <div class= "course-card-sub">
                        <% if course.category %>
                            <%= image_tag("#{course.category}.jpg", class: "course-card-img") %>
                        <% end %>

                        <div class="courses-card-info">
                            <h3 class="card-title  <%= course.category%>"><%= course.name %></h3>
                            <h5 class="card-title"><%= course.title %></h5>
                            <p class="card-name"> <%= course.user.first_name %> <%= course.user.last_name %></p>
                            <p class="card-price"><%= course.price %> $</p>
                            <%# <p class="card-price">2h </p> %>

                            <h6 class="card-name"><%= course.name %></h6>
                        </div>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

<!-------------->

app/views/courses/show.html.erb
<div class = "course-show-container">
    <!-------------->
    <div class="courses-show-banner-container">
        <h3 class="courses-show-category <%= @course.category%>"><%= @course.category.capitalize %></h3>
        <div class="courses-show-banner-container-sub0">
            <div class="courses-show-banner-container-sub">
                <div class="courses-show-banner-gradient"></div>
                <%= image_tag("#{@course.category}.jpg", class: "course-show-img") %>
                <div class="courses-show-banner-info">
                    <p class="courses-show-rating"><%= @course.rating %></p>
                    <h2 class="courses-show-title <%= @course.category%>"><%= @course.title %> </h2>
                    <h2 class="courses-show-name"><%= @course.name%></h2>
                </div>
            </div>
            <div class= "course-show-teacher-img-container">
                <%= link_to teacher_path(@course.user) do %>
                <% if @course.user.url_avatar %>
                <img src="<%= @course.user.url_avatar %>" alt="profile one" class= "course-show-teacher-img">
                <% else %>
                <%= image_tag("avatar-neutre.jpg", class: "teacher-card-img-sub") %>
                <% end %>
                <% end %>
            </div>
            <h2 class="courses-show-teacher"><%= @course.user.first_name%> <%= @course.user.last_name%></h2>
        </div>
    </div>
    <!-------------->
    <div class="home-container">
        <div class="aka-line-80-primary-container">
            <div class="aka-line-80-primary"></div>
        </div>
    </div>
    <!-------------->
    <div class="course-content-container">
        <h2 class="courses-content-Chapiter">Chapiter 1</h2>
        <h2 class="courses-content-title <%= @course.category%>"><%= @course.title %> </h2>
        <p><%= @course.content %>
            <div class="course-content-container-gradient"></div>
        </p>
    </div>
        <%# <div class= 'gotobottom btn-aka-light square'><i class="fa-solid fa-arrow-down"></i></div> %>
    <%# <p><%= @scrap %>
    <%# <iframe src='https://www.youtube.com/watch?v=LRmhKf8-ZSk&ab_channel=Deep%26Elegant' frameborder='0' allowfullscreen></iframe> %>
    <!-------------->
    <div class="home-container">
        <div class="aka-line-80-primary-container">
            <div class="aka-line-80-primary"></div>
        </div>
    </div>
    <!-------------->
    <div class="upcoming-sessions">
        <p>UPCOMING SESSIONS</p>
    </div>
    <!-------------->
    <div class="home-container">
        <div class="aka-line-60-grey-container">
            <div class="aka-line-60-grey"></div>
        </div>
    </div>
    <!-------------->
    <div class = "session-container">
        <% @classes.each do |classe| %>
        <div class="session-container-sub">
            <div class="session-img-container">
                <%= image_tag("#{@course.category}.jpg", class: "session-img") %>
            </div>
            <div class="session-info-container">
                <h3 class="<%= @course.category%>" >  <%= classe.name %></h3>
                <p> <i class="fa-solid fa-calendar-days"></i> <%= classe.start_date.strftime("%d / %m / %Y") %></p>
                <p> <i class="fa-solid fa-hourglass-start"></i> <%= classe.start_date.hour %>h00</p>
                <p> <i class="fa-solid fa-hourglass-end"></i> <%= classe.end_date.hour - classe.start_date.hour %>h00</p>
            </div>
            <div class="session-enrollment-container">
                <% if classe.start_date > Time.now + 12.hours%>
                    <% if current_user %>
                        <% if classe.enrollments.any? { |element| element.user_id == current_user.id  } %>
                            <p style="color:pink">Already enroll</p>
                            <%= button_to "Cancel", enrollment_path(classe.enrollments.select {|k| current_user.id}), method: :delete, class: 'btn-aka', data: {turbo_confirm: 'are you sure ?'}  %>
                        <% else %>
                            <p style="color:green"><i class="fa-regular fa-clock"></i> <%= Time.at(classe.start_date - Time.now).utc.strftime("%Hh%Mmin") %></p>
                            <p style="color:green">Enrollment Open</p>
                            <p style="color:green"> Available seats <%=  classe.max_people - classe.enrollments.count %> / <%=  classe.max_people %></p>
                            <%= button_to "Enroll now", class_enrollments_path(classe), method: :post, class: 'btn-aka-light-login', data: {turbo_confirm: 'are you sure ?'}  %>
                        <% end %>
                    <% else %>
                        <p style="color:green"> still <%=  classe.max_people - classe.enrollments.count %> / <%=  classe.max_people %></p>
                        <p>you have to login if you want enroll</p>
                        <%= button_to "Login", new_user_session_path, class: "btn-aka-light-login" %>
                    <% end %>
                <% else %>
                        <p style="color:red">Enrollment Closed</p>
                        <p>Enrollment close 12h before class date</p>
                <% end %>
            </div>
        </div>
        <%# <div class="home-container"> %>
        <%# <div class="aka-line-60-grey-container">
            <div class="aka-line-60-grey"></div>
            </div> %>
        <%# </div> %>
        <% end %>
        <%# </div> %>
    </div>
</div>